# Generated by Django 5.2.14 on 2026-06-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowerKind",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="product",
            name="flower_kinds",
            field=models.ManyToManyField(blank=True, related_name="products", to="catalog.flowerkind"),
        ),
    ]
